# Generated by Django 5.0.7 on 2024-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_block_images/'),
        ),
    ]
