# Generated by Django 5.0.7 on 2024-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contentblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='text_type',
            field=models.CharField(blank=True, choices=[('heading', 'Heading'), ('subheading', 'Subheading'), ('list', 'List'), ('normal', 'Normal Text')], max_length=20, null=True),
        ),
    ]
