# Generated by Django 5.0.7 on 2024-08-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_service_desc_remove_service_image_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='case_study',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='service',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
