# Generated by Django 5.0.7 on 2024-08-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_contentblock_blog_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='name',
        ),
        migrations.AddField(
            model_name='formdata',
            name='company',
            field=models.CharField(default='Default Company', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='designation',
            field=models.CharField(default='Default Designation', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='firstName',
            field=models.CharField(default='Default First Name', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='lastName',
            field=models.CharField(default='Default Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content_type',
            field=models.ForeignKey(default='blog', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
