# Generated by Django 5.0.7 on 2024-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_formdata_name_formdata_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(default='Default Company', max_length=50),
        ),
    ]
