# Generated by Django 5.0.7 on 2024-08-12 18:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_testimonial_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='client_images/', validators=[app.models.validate_svg_or_image]),
        ),
    ]
